### ISSUE TITLE
How to generate other types of output (e.g. Markdown)?

### ISSUE THREAD

**Issue by gberger** [coffeedoc/codo#155]
I like using codo's tags to document my project.

However, I need to get output in some other form, be it Markdown, or some giant JSON, or whatever. 

I want to use this output to publish the documentation in other formats; the generated site  does not suit my needs.

**Comment by steel** [comment]
FYI. I needed json and couldn't find anything that already existed so I built my own json template: https://www.npmjs.com/package/codo-theme-json
