### ISSUE TITLE
Can't parse properties that default to function calls

### ISSUE THREAD

**Issue by ben** [coffeedoc/codo#163]
I'm trying to document a Knockout viewmodel, where most of the properties' default values are the return value from `ko.observable()` or `ko.observableArray()`. However, codo isn't seeing these values properly. Here's an example:

```coffeescript
class ViewModel
  # @property [observable/string] This means something.
  propertyA: ko.observable 'abc'

  # @property [observable/string] This means something else.
  propertyB: 'def'

  constructor: ->
    propertyB = ko.observable 'def'
```

Running this class through codo produces a `class/ViewModel.html` which lists `propertyB`, but not `propertyA`. Can anything be done?

**Comment by inossidabile** [comment]
That's the nature of JS. You can express anything in thousands ways to achieve roughly the same. Unfortunately in terms of lexer it leads to incredible amount of possible configurations that can work as properites. Codo is limited to support exactly what it states it supports in README. If you need the other format you can open PR and we can discuss it based on your samples.
