### ISSUE TITLE
Variables Summary for files doesn't work properly

### ISSUE THREAD

**Issue by timaschew** [coffeedoc/codo#174]
I found out that _everything_ that is defined in the root context of a file and what is exported via `module.exports` generates an entry in the doc.
But it depends on the syntax, for instance this works: `foo = require('foo').bar` but this doesn't: `foo = require('foo')`
The short version `{foo} = require('foo')` doesn't work as well.

Is this behavior desired?

**Comment by inossidabile** [comment]
Yes, I'm interested in PR. I never had any use-cases that would involve documenting variables. In fact this part of Codo is just a BC thing that came from version 1 and original author.
