### ISSUE TITLE
cannot omit @private in the docs

### ISSUE THREAD

**Issue by timaschew** [coffeedoc/codo#175]
It seems that the behavior was changed, because I found some issues that was fixed.

But for now it doesn't work anymore, but the documentation tells something different:

` --private, -p       Show privates                             [default: false]`

This options is ignored, it's always the same result: The methods have a `private` tag.

In the source code I don't see any conditions for this `private` option.

**Comment by thammi** [comment]
Please include the patch/fix. Would like to use this documented switch to create private and public documentation.
