### ISSUE TITLE
Doesn't work with Ember.js projects

### ISSUE THREAD

**Issue by amk221** [coffeedoc/codo#182]
I'm working on an Ember-cli project

```
# My controller
# @example
#   Blah
MyController = Ember.Controller.extend
  # My property
  # @return {String}
  myProperty: (-> 'blah').property()
```

However the above is never noticed by codo.

**Comment by luketheobscure** [comment]
Every few weeks I come back and look at this comment and get really sad for a while.

**Comment by inossidabile** [comment]
@luketheobscure the new Codo has pretty extensible structure that you can inherit and override. Fork it, change the way it seeks for classes and you are done.
