### ISSUE TITLE
Why do I get hash symbol (#) before method signature?

### ISSUE THREAD

**Issue by markogresak** [coffeedoc/codo#187]
I'm trying to figure out how `codo` works, but I have this strange and annoying problem. I'm looking at [dropbox api](http://coffeedoc.info/github/dropbox/dropbox-js/master/) docs as an example, and I can't figure out why I get different output with same doc entry.

My output:

    # (void) constructor(xhr, method, url) 

Desired outout:

    - (void) constructor(xhr, method, url)

It's not that big of a deal, but the `#` just feels like I've made some mistake in documenting since it's the symbol coffee uses as comment. What am I doing wrong?

**Comment by tristanjahier** [comment]
I've got the same output, and I don't think that' s a mistake... Are you sure that's an issue?
Maybe you could customize it though.

**Comment by markogresak** [comment]
The problem is that `#` doesn't represent any access access modifiers, I was expecting `-` for private and `+` for public (defaults to public, `@private` for private), like seen in the dropbox api. Do I need a special setting for this kind of behaviour?

**Comment by tristanjahier** [comment]
Ok, in my case I haven't specified anything. Maybe it has something to do with `--private` option but I'm not sure...

**Comment by inossidabile** [comment]
Privates do not exists in Javascript even tho can be manually specified by `@private`. We use plus and minus signs to distract static and dynamic methods. Hash symbol goes to the cases where the usage is unclear (like mixins where a method can be dynamic or static depending on usage).

**Comment by markogresak** [comment]
I know there is no privates, I was talking about using @private which I saw in Dropbox's code. So how does one make static/dynamic explicit?

**Comment by inossidabile** [comment]
By using Coffee-script syntax :). It has it defined.
