### ISSUE TITLE
Webhook no longer works

### ISSUE THREAD

**Issue by topliceanu** [coffeedoc/codo#189]
I'm trying to configure automated docs generation and hosting on coffeedocs.info using codo for [my library](https://github.com/topliceanu/mortimer)

I've tried two things in my project's Settings > Webhooks&Services
1. added coffeedoc.info as a service 
2. setup a hook request to `http://coffeedoc.info/checkout`, `Content-type: application/x-www-form-urlencoded`, no Secret and triggered just on push. The reponse from coffeedoc.info is `200 OK` with an empty body. Is that correct?

Is there something I'm missing? Is there any guide on how to setup coffeedocs?
Thank you! and sorry for contacting you this way, I couldn't find your email :(

**Comment by topliceanu** [comment]
I should mention that on localhost, documentation is generated correctly.

**Comment by aseemk** [comment]
This was likely <https://github.com/coffeedoc/coffeedoc.info/issues/9>, which is fixed now.

**Comment by topliceanu** [comment]
Yes this is no longer an issue, the docs do show up. 
@aseemk I think this issues should be closed

**Comment by aseemk** [comment]
I'm unable to close this. I assume only @inossidabile can?

**Comment by topliceanu** [comment]
:D
