### ISSUE TITLE
coffeedoc.info is down

### ISSUE THREAD

**Issue by aseemk** [coffeedoc/codo#192]
Tweeted, but realized a GitHub Issue may be more appropriate.

http://coffeedoc.info/

> nodejitsu
> 400
> www.coffeedoc.info is currently stopped

**Comment by ChALkeR** [comment]
https://github.com/coffeedoc/coffeedoc.info/issues/9

**Comment by aseemk** [comment]
Oh whoops, should have posted there, you're right. Thanks.
