### ISSUE TITLE
Support for .litcoffee and .coffee.md

### ISSUE THREAD

**Issue by chmac** [coffeedoc/codo#200]
We're using a lot of literate coffeescript these days and would love to be able to parse documentation out of it. I know that might seem crazy, because the code is documentation in literate coffeescript, but it could be useful for extracting API docs and other stuff like that.

My grepping of the codo codebase suggests there's currently no support for `.litcoffee` or `.coffee.md` files (the latter being our weapon of choice).

Thanks for releasing awesome code.

#featureRequest

**Comment by DecipherCode** [comment]
+1

**Comment by inossidabile** [comment]
It does seem crazy. Please provide a reasonable use case that we could discuss.

**Comment by chmac** [comment]
We could write the docs inline and then publish without actually publishing the source itself. We're no longer working on that project, so my personal need has gone, but I can imagine use cases...

**Comment by inossidabile** [comment]
I still don't get it. How exactly are you going to combine these two competing paradigms and what benefits does it give? Generating docs and publishing them without sources is a common use-case for both tools. It doesn't explain anything.

**Comment by chmac** [comment]
I don't see the competition. Literate coffee allows developers to read the code and documentation easily inline on GitHub, but we still want to extract the docs separately and publish those to the users of the API (we built a public facing API).

**Comment by inossidabile** [comment]
There are definitely other possible use-cases, I agree. Can you post any kind of short sample file featuring these two working together?

**Comment by chmac** [comment]
Not off the top of my head. Sitting in Frankfurt airport waiting for a flight posting on my phone. :-)

**Comment by inossidabile** [comment]
Yeah, when you get a chance. Thanks.

**Comment by chmac** [comment]
That project is no longer under development, so I won't have time personally to write up an example, it's been a while. :-) Maybe somebody else will do so in due course...
