### ISSUE TITLE
input file specificity

### ISSUE THREAD

**Issue by wjagodfrey** [coffeedoc/codo#201]
Hi guys,

There doesn't seem to be a way to specify which files get doc'ed. This is an issue for me, because Codo is pulling in my installed node_modules. It's also checking a number of unnecessary files which takes a while. My coffee is in one directory and I want to just tell it to look there.

A config .json file would be awesome.

Thanks,
Wilfred

**Comment by inossidabile** [comment]
You didn't read readme do you?

**Comment by wjagodfrey** [comment]
Issue wasn't scoping to a specific directory, but ignoring specific files and directories. Avoiding `node_modules` was only a side issue.

If there is something in the README regarding that, then that's my mistake. I also apologise for not making myself clearer.
