### ISSUE TITLE
Suggested feature: @inheritdoc tag

### ISSUE THREAD

**Issue by jusopi** [coffeedoc/codo#203]
One of the tedious tasks of making API docs is having to make sure that overridden APIs in subclasses have the same docs text found in their super classes.  It would be nice to have some sort of *lookup* feature that when the parsers sees the `@inheritdoc` string, it will try to find the original API docs text in the super class and build from there.  An example of this can be found in the [asdocs generator for Flash/Actionscript](http://help.adobe.com/en_US/flex/using/WSd0ded3821e0d52fe1e63e3d11c2f44bc36-7ff6.html)

      class Base
           
           #
           # A method
           #
           foo: -> 

       class Subbase extends Base

           #
           # @inheritdoc
           #
           foo: ->
                super

**Comment by inossidabile** [comment]
I'm not sure it's gonna be too useful in Coffee reality. However I will accept PR if you prepare one.
