### ISSUE TITLE
Implement optionality marker for @param

### ISSUE THREAD

**Issue by zhangkaiyulw** [coffeedoc/codo#204]

**Comment by hildjj** [comment]
The node.js API docs are generated with square brackets around the optional parameters.  I like that a lot.  Something as simple as the description ending in `(optional)` would be perfectly adequate.

**Comment by mitar** [comment]
Why was this closed? I would also need this feature.

**Comment by inossidabile** [comment]
Because you can specify "optional" manually and this is not a PR.

**Comment by mitar** [comment]
But you cannot specify that for the signature.

**Comment by E-geek** [comment]
Please do not forget the default.
Example (as [JSDoc param](http://usejsdoc.org/tags-param.html) ):
```coffeescript 
# @param {String} [name] optional value
# @param {Number} [input = 1] optional with default value
```
Or other format:
```coffeescript 
# @param {String} name optional value [optional]
# @param {Number} input optional with default value [default = 1]
```
