### ISSUE TITLE
Properties for mixin

### ISSUE THREAD

**Issue by akfish** [coffeedoc/codo#205]
Codo doesn't support properties in mixins, so there is no way to document code like this:
```coffee
###
The mixin
@mixin
###
TheMixin = 
  # @property [string] whatever property <- not documented
  prop: 'whatever'

###
The class
@include TheMixin
###
class TheClass
```
It would be great if @property can be used in mixins.

**Comment by inossidabile** [comment]
I like that but the implementation can take time that I don't have atm. PRs are welcome.
