### ISSUE TITLE
Accept namespace for method names.

### ISSUE THREAD

**Issue by dirtyhenry** [coffeedoc/codo#212]
For method defined in a namespace (let's say `Bar.foo`), the method appears as `Bar` only in the documentation.

For instance, for: 

    Bar.foo = (arg1) ->
        console.debug arg1

The documentation for the file will appear as: 

    ~ (void) Bar(arg1)

instead of 

    ~ (void) Bar.foo(arg1)

**Comment by inossidabile** [comment]
Yes. Because there's no such thing as a "method namespace". If you refer to mixin – you should use the syntax given in README samples. Same goes to class. What you give an instance is a meta-magical modification of something that's defined somewhere else. Codo can't support it.
