### ISSUE TITLE
'use strict' might be causing problems

### ISSUE THREAD

**Issue by mkautzmann** [coffeedoc/codo#214]
Hello, anyone else having problems when code includes the `'use strict'` statement?

I'm getting the following error in the screenshot when using it, normal behavior when removing the line.

![codo_use_strict_screen](https://cloud.githubusercontent.com/assets/1051644/10591977/e7a70008-7697-11e5-89c2-bc4b80eaad6b.jpg)

**Comment by inossidabile** [comment]
Please check if it's still the case with master.
