### ISSUE TITLE
Link to mixin method fails to parse correctly

### ISSUE THREAD

**Issue by CodeLenny** [coffeedoc/codo#237]
A link to a mixin method in the body of a comment (`{MyMixin#foo}`) fails to parse at all, and prints the full string including brackets.  An `@see` link points to `class/MyMixin#foo` rather than `mixins/MyMixin#foo`, which fails to load.

```coffee
###
My Mixin
@mixin
###
MyMixin:
  foo: (bar) -> console.log bar
```

```coffee
###
How about seeing {MyMixin#foo}?
@see MyMixin#foo
class MyClass
  constructor: -> @foo()
```

**Comment by inossidabile** [comment]
That's because you aren't using the correct notation. The methods of Modules aren't static nor dynamic. We are using the `~` sign to refer those. So if you change it to `MyMixin~foo`  things will roll.

**Comment by CodeLenny** [comment]
Gotcha, thank you!  That makes my documentation much cleaner.
